import { ImageSourcePropType } from 'react-native';
export const CATEGORIES_DATA: { [key: string]: { id: string; name: string; image?: ImageSourcePropType }[] } = {
  'Fruits': [
    { id: 'f1', name: 'Blueberry',image: require('../assets/blueberry.jpg') },
    { id: 'f2', name: 'Raspberry',image: require('../assets/raspberry.jpg') },
    { id: 'f3', name: 'Avacodo',image: require('../assets/avocado.jpg') },
    { id: 'f4', name: 'Tangerine' },
    { id: 'f5', name: 'Bananas' },
    { id: 'f6', name: 'Lychee' },
    { id: 'f7', name: 'Strawberry' },
    { id: 'f8', name: 'Grape' },
    { id: 'f9', name: 'Cherry Tomato' },
    { id: 'f10', name: 'Watermelon' },
    { id: 'f11', name: 'Guava' },
    { id: 'f12', name: 'Mangosteen' },
    { id: 'f13', name: 'Dragon Fruit' },
    { id: 'f14', name: 'Pineapple'}
  ],
  'Household': [
    { id: 'h1', name: 'Paper Towel' },
    { id: 'h2', name: 'Tissue' },
    { id: 'h3', name: 'Toilet Paper' },
    { id: 'h4', name: 'Toothpaste' },
    { id: 'h5', name: 'Toothbrush' },
    { id: 'h6', name: 'Facial Cleanser' },
    { id: 'h7', name: 'Shampoo' },
    { id: 'h8', name: 'Shower Gel' },
    { id: 'h9', name: 'Sanitary Pads' },
    { id: 'h10', name: 'Tampons' },
    { id: 'h11', name: 'Cotton Pads' },
    { id: 'h12', name: 'Washing-up Liquid' },
    { id: 'h13', name: 'Laundry Pods' },
    { id: 'h14', name: 'Cling Film' },
    { id: 'h15', name: 'Resealable Bags' },
    { id: 'h16', name: 'Parchment Paper' },
    { id: 'h17', name: 'Tin Foil' },
    { id: 'h18', name: 'Wet Wipes' },
  ],
  'Convenience': [
    { id: 'c1', name: 'Crisps' },
    { id: 'c2', name: 'Spicy Prince Snack' },
    { id: 'c3', name: 'Shin Ramen' },
    { id: 'c4', name: 'Samyang Hot Chicken Ramen' },
    { id: 'c5', name: 'Alkaline Noodles' },
    { id: 'c6', name: 'Sliced Bread' },
    { id: 'c7', name: 'Bread' },
  ],
  'Beverages': [
    { id: 'b1', name: 'Tea' },
    { id: 'b2', name: 'Coconut Water' },
    { id: 'b3', name: 'Electrolyte Water' },
  ],

  'Dairy & Eggs': [
    { id: 'd1', name: 'Cream Cheese' },
    { id: 'd2', name: 'Egg' },
    { id: 'd3', name: 'Soya Yogurt' },
    { id: 'd4', name: 'Soya Milk' },
    { id: 'd5', name: 'Tofu' },
    { id: 'd6', name: 'Butter' },
    { id: 'd7', name: 'Cheddar Cheese' },
    { id: 'd8', name: 'Century Egg' },
  ],

  'Frozen': [
    { id: 'f1', name: 'Har Gow' },
    { id: 'f2', name: 'Wonton' },
    { id: 'f3', name: 'Siu Mai' },
    { id: 'f4', name: 'Edemame' },
    { id: 'f5', name: 'Fried Chicken' },
    { id: 'f6', name: 'Dumplings' },
  ],
  'Meat & Seafood': [
    { id: 'm1', name: 'Beef' },
    { id: 'm2', name: 'Chicken Thighs' },
    { id: 'm3', name: 'Chicken Breast' },
    { id: 'm4', name: 'Prawn' },
    { id: 'm5', name: 'Salmon' },
    { id: 'm6', name: 'Pork Ribs' },
    { id: 'm7', name: 'Pork Belly' },
  ],


}
